In [1]:

import numpy as np

In [2]:
l1=[1,2,3]

In [4]:
arr=np.array(l1)

In [5]:
arr

array([1, 2, 3])

In [11]:
type(arr)

numpy.ndarray

In [13]:
arr.size

3

In [14]:
arr.shape

(3,)

In [16]:
np.ndim(arr)

1

In [17]:
sum(arr)

6

In [6]:
z=[11,4,0.9]

In [9]:
arr1=np.array(z)

In [10]:
arr1

array([11. ,  4. ,  0.9])

In [12]:
type(arr1)

numpy.ndarray

In [20]:
arr1.size

3

In [21]:
arr1.shape

(3,)

In [22]:
np.ndim(arr1)

1

In [23]:
sum(arr1)

15.9

In [24]:
l2=[[1,2,3],[4,5,6],[7,8,9]]

In [26]:
arr2=np.array(l2)

In [27]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2.size

9

In [29]:
arr2.shape

(3, 3)

In [30]:
np.ndim(arr2)

2

In [33]:
arr3=arr2.reshape(1,9)

In [34]:
arr3

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
arr4=arr2.reshape(1,9)

In [40]:
arr4

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [47]:
arr5=np.arange(1,10)

In [48]:
arr5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr5.size

9

In [50]:
arr5.shape

(9,)

In [51]:
arr6=arr5.reshape(3,3)

In [52]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.ndim(arr6)

2

In [55]:
arr6.size

9

In [56]:
arr6.shape

(3, 3)

In [57]:
np.zeros((2,3))  #2 is row,3 is coloum

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.eye(4)    #4indicates no.of matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [61]:
np.linspace(0,10,7)  #divides into equal parts  from 0 to 10 into 7 equal parts

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [63]:
np.linspace(1,6,8)

array([1.        , 1.71428571, 2.42857143, 3.14285714, 3.85714286,
       4.57142857, 5.28571429, 6.        ])

In [64]:
np.linspace(1,6,2)

array([1., 6.])

In [65]:
np.random.rand(3,4)    #3 row & 4 coloum

array([[0.88485859, 0.17102071, 0.31085144],
       [0.10913993, 0.47802529, 0.34361757]])

In [67]:
np.random.randn(2,3)   #n for normal distribution:part of statistics

array([[ 0.09311491, -2.44349905, -0.16858278],
       [-0.41149272, -0.53087748,  1.94271186]])

In [68]:
np.random.randint(4,40,20)   #it will take 20 different values from 4(inclusive)and 40(exclusive)

array([15,  7,  7, 24, 33, 30, 17, 21,  5, 19, 38,  8, 36, 19, 21,  8, 31,
       18, 10, 25])

In [1]:
np.random.randint(50,size=(3,4))  #from 0(included)to 50(excluded)....2dimensional array

NameError: name 'np' is not defined

# float values will not be considered

In [70]:
np.random.randint(-2,20,10)

array([13,  3,  7,  1, 11,  2,  8,  1,  5, -1])

In [72]:
np.random.randint(-50,0,size=(3,4))

array([[-20,  -1, -39, -41],
       [ -9, -33,  -7, -29],
       [-14, -26, -36, -24]])

# Revision

In [73]:
a1=[[30,40,50,60],[13,23,33,43],[0,1,2,3],[100,200,300,400]]

In [74]:
arr7=np.array(a1)

In [75]:
arr7

array([[ 30,  40,  50,  60],
       [ 13,  23,  33,  43],
       [  0,   1,   2,   3],
       [100, 200, 300, 400]])

In [76]:
arr7.size

16

In [77]:
arr7.shape

(4, 4)

In [78]:
np.ndim(arr7)

2

In [79]:
sum(arr7)

array([143, 264, 385, 506])

# Another Method

In [80]:
y=[30,40,50,60,13,23,33,43,0,1,2,3,100,200,300,400]

In [81]:
arr8=np.array(y)

In [82]:
arr8

array([ 30,  40,  50,  60,  13,  23,  33,  43,   0,   1,   2,   3, 100,
       200, 300, 400])

In [84]:
arr9=arr8.reshape(4,4)

In [85]:
arr9

array([[ 30,  40,  50,  60],
       [ 13,  23,  33,  43],
       [  0,   1,   2,   3],
       [100, 200, 300, 400]])

In [86]:
np.ndim(arr9)

2

# to convert 1d to 2d we use reshaping

In [90]:
arr9[0,0]    #indexing[R,C]

30

In [91]:
arr9[1,1]

23

In [93]:
arr9[:,:]

array([[ 30,  40,  50,  60],
       [ 13,  23,  33,  43],
       [  0,   1,   2,   3],
       [100, 200, 300, 400]])

In [94]:
arr9[0:2,1:3]

array([[40, 50],
       [23, 33]])

In [95]:
arr9[1:3,2:]

array([[33, 43],
       [ 2,  3]])

In [96]:
arr9[0:,1:3]

array([[ 40,  50],
       [ 23,  33],
       [  1,   2],
       [200, 300]])

In [97]:
arr9[2:,2:]

array([[  2,   3],
       [300, 400]])

In [99]:
arr9[0:2,]

array([[30, 40, 50, 60],
       [13, 23, 33, 43]])

In [100]:
arr9[0:2,]

array([[30, 40, 50, 60],
       [13, 23, 33, 43]])

In [101]:
arr9[,0:2]

SyntaxError: invalid syntax (<ipython-input-101-d4eee49ea1c7>, line 1)

In [102]:
arr9.sum()

1298

In [103]:
arr9[[0,2],[1,2]]

array([40,  2])

In [104]:
a=[1,2,3,4]

In [105]:
b=[5,6,7,8]

In [106]:
arr10=np.array(a)

In [107]:
arr10

array([1, 2, 3, 4])

In [108]:
arr11=np.array(b)

In [109]:
arr11

array([5, 6, 7, 8])

In [110]:
arr12=arr11.reshape(2,2)

In [111]:
arr12

array([[5, 6],
       [7, 8]])

In [112]:
arr13=arr10.reshape(2,2)

In [113]:
arr13

array([[1, 2],
       [3, 4]])

In [114]:
c=np.add(arr12,arr13)

In [115]:
c

array([[ 6,  8],
       [10, 12]])

In [118]:
c=np.subtract(arr13,arr12)

In [119]:
c

array([[-4, -4],
       [-4, -4]])

In [120]:
c=np.multiply(arr13,arr12)

In [121]:
c

array([[ 5, 12],
       [21, 32]])

In [122]:
c=np.divide(arr13,arr12)

In [123]:
c

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [124]:
arr13/arr12

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

# Alternate method for operatos

In [125]:
arr13==arr12

array([[False, False],
       [False, False]])

In [126]:
arr13!=arr12

array([[ True,  True],
       [ True,  True]])

In [127]:
arr13<2

array([[ True, False],
       [False, False]])

In [128]:
arr12<2

array([[False, False],
       [False, False]])

In [129]:
arr13<arr12

array([[ True,  True],
       [ True,  True]])

# a.ravel will convert any dimensional to 1D

In [131]:
arr13.ravel()

array([1, 2, 3, 4])

# Filtering

In [132]:
arr13

array([[1, 2],
       [3, 4]])

In [134]:
arr13[arr13<3]

array([1, 2])

In [135]:
arr13[arr13==4]

array([4])

In [136]:
arr13[arr13>3]

array([4])

In [138]:
arr13[arr13!=4]

array([1, 2, 3])

# gapping

In [139]:
l=[1,2,3,4,5,6,7,8,9,10]

In [141]:
l[0:9:2]

[1, 3, 5, 7, 9]

In [142]:
np.unique(arr13)   #similar to set

array([1, 2, 3, 4])